# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Build checks"
  lane :checks do
    gradle(task: "clean")
    gradle(task: "diktatCheck")
    gradle(task: "buildHealth")
    gradle(task: "kotlinTestRule")
    gradle(task: "build")
  end

  desc "Benchmarks"
  lane :benchmarks do
    sh "sh ../ci/microbenchmarks.sh"
    sh "sh ../ci/macrobenchmarks.sh"
    sh "sh ../ci/analyse_benchmarks.sh"
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
